name: Dependabot Composer Fix

on:
  push:
    branches:
      - 'dependabot-test/composer/**'

jobs:
  composer:
    runs-on: ubuntu-latest

    name: Composer Update

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: gd
          coverage: none
          tools: composer

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get updated package
        id: package-info
        run: echo "::set-output name=name::$(git rev-parse --abbrev-ref HEAD | cut -d "/" -f 3-4 | cut -d "-" -f 1)"

      - name: Rollback update
        run: git checkout HEAD^ composer.lock

      - name: Update dependency
        run: composer update ${{ steps.package-info.outputs.name }} --no-progress

      - name: Commit changes
        run: |
          git add composer.lock
          git config user.name gapple
          git config user.email geoff@no-reply.gapple.ca
          git commit -m "[dependabot skip] Fix composer package update"
          git push
