name: Dependabot Composer Fix

on: pull_request_target

permissions:
  pull-requests: read
  contents: write

jobs:
  composer:
    runs-on: ubuntu-latest

    if: ${{ github.actor }} == 'dependabot[bot]' && ${{ startsWith(github.head_ref, 'dependabot/composer') }}

    name: Composer Update

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: composer

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Rollback dependabot changes
        run: |
          git fetch --no-tags --no-recurse-submodules --depth=1 origin +${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }} -- composer.lock

      - name: Update dependency
        run: composer update ${{ steps.dependabot-metadata.outputs.dependency-names }} --no-progress

      - name: Commit and push changes
        run: |
          git add composer.lock
          git config user.name gapple
          git config user.email geoff@no-reply.gapple.ca
          git commit -m "[dependabot skip] Fix composer package update"
          git push origin HEAD:${{ github.head_ref }}
